# Generated by Django 4.1.7 on 2023-05-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_like_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
