# Generated by Django 4.1.7 on 2023-03-31 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='imageURL',
            new_name='img_url',
        ),
    ]
